# Generated by Django 4.2.1 on 2023-06-07 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataManager', '0002_picture_remove_route_picture_remove_location_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='picture',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='route',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
