# Generated by Django 4.2.1 on 2023-06-07 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataManager', '0003_location_views_picture_likes_route_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='route',
            name='pictures',
        ),
    ]
