# Generated by Django 4.2.1 on 2023-06-07 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataManager', '0004_remove_location_picture_remove_route_pictures'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='views',
        ),
        migrations.RemoveField(
            model_name='route',
            name='views',
        ),
    ]
