# Generated by Django 4.2.1 on 2023-06-07 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataManager', '0005_remove_location_views_remove_route_views'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Picture',
        ),
        migrations.AddField(
            model_name='location',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='route',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
