# Generated by Django 4.2.1 on 2023-06-07 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataManager', '0007_picture_location_pictures_route_pictures'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='pictures',
        ),
        migrations.RemoveField(
            model_name='location',
            name='views',
        ),
        migrations.RemoveField(
            model_name='route',
            name='pictures',
        ),
        migrations.RemoveField(
            model_name='route',
            name='views',
        ),
        migrations.AddField(
            model_name='location',
            name='picture',
            field=models.ImageField(default='default_image.jpg', upload_to='locations/'),
        ),
        migrations.AddField(
            model_name='route',
            name='picture',
            field=models.ImageField(default='default_image.jpg', upload_to='routes/'),
        ),
        migrations.DeleteModel(
            name='Picture',
        ),
    ]
