# Generated by Django 4.2.1 on 2023-06-07 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataManager', '0008_remove_location_pictures_remove_location_views_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_type', models.CharField(choices=[('l', 'Location'), ('r', 'Route')], max_length=1)),
                ('image', models.ImageField(upload_to='routes/')),
                ('likes', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='location',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='route',
            name='picture',
        ),
        migrations.AddField(
            model_name='location',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='route',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='location',
            name='pictures',
            field=models.ManyToManyField(to='dataManager.picture'),
        ),
        migrations.AddField(
            model_name='route',
            name='pictures',
            field=models.ManyToManyField(to='dataManager.picture'),
        ),
    ]
