# Generated by Django 4.2.1 on 2023-06-02 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pageManager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='picture',
            field=models.ImageField(default='default_image.jpg', upload_to='locations/'),
        ),
    ]
