# Generated by Django 4.2.1 on 2023-06-04 18:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dataManager', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('displayName', models.CharField(default=None, max_length=150)),
                ('profilePicture', models.ImageField(upload_to='files/profilePicture')),
                ('bio', models.CharField(max_length=200)),
                ('completedRoutes', models.ManyToManyField(related_name='completedRoutes', to='dataManager.route')),
                ('favoritedRoutes', models.ManyToManyField(related_name='favoritedRoutes', to='dataManager.route')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
