# Generated by Django 4.2.1 on 2023-06-07 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataManager', '0002_picture_remove_route_picture_remove_location_picture_and_more'),
        ('accountManager', '0002_alter_profile_bio_alter_profile_completedroutes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='postedRoutes',
            field=models.ManyToManyField(blank=True, related_name='postedRoutes', to='dataManager.route'),
        ),
    ]
