# Generated by Django 4.2.1 on 2023-06-07 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataManager', '0006_delete_picture_location_views_route_views'),
        ('accountManager', '0004_remove_profile_postedroutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='postedRoutes',
            field=models.ManyToManyField(blank=True, related_name='postedRoutes', to='dataManager.route'),
        ),
    ]
