# Generated by Django 4.2.1 on 2023-06-07 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataManager', '0009_picture_remove_location_picture_remove_route_picture_and_more'),
        ('accountManager', '0006_remove_profile_postedroutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='postedRoutes',
            field=models.ManyToManyField(blank=True, related_name='postedRoutes', to='dataManager.route'),
        ),
    ]
